# Auto-generated by Gorun PaaS
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download 2>/dev/null || true
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
