package deployer

import (
	"bytes"
	"fmt"
	"net/http"
	"strings"
)

// SyncCaddyConfig generates a Caddyfile for all configured projects and sends it to Caddy Admin API.
func (d *Deployer) SyncCaddyConfig() error {
	projects, err := d.store.ListProjects()
	if err != nil {
		return fmt.Errorf("failed to list projects: %w", err)
	}

	var caddyfileBuilder strings.Builder
	caddyfileBuilder.WriteString("# Auto-generated by Gorun PaaS\n\n")

	for _, proj := range projects {
		domains, err := d.store.ListDomains(proj.ID)
		if err != nil || len(domains) == 0 {
			continue // skip if no domains
		}

		color := GetActiveColor(proj.ID)
		if color == "" {
			color = "blue" // default fallback
		}

		port := HostPort(proj.ID, color)

		var domainNames []string
		for _, d := range domains {
			domainNames = append(domainNames, d.Domain)
		}

		caddyfileBuilder.WriteString(fmt.Sprintf("%s {\n", strings.Join(domainNames, ", ")))
		caddyfileBuilder.WriteString(fmt.Sprintf("    reverse_proxy localhost:%d\n", port))
		caddyfileBuilder.WriteString("}\n\n")
	}

	caddyfileContent := caddyfileBuilder.String()

	// Send to Caddy Admin API
	req, err := http.NewRequest("POST", "http://localhost:2019/load", bytes.NewBufferString(caddyfileContent))
	if err != nil {
		return fmt.Errorf("failed to create caddy request: %w", err)
	}
	req.Header.Set("Content-Type", "text/caddyfile")

	client := &http.Client{}
	resp, err := client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to sync with caddy: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode >= 400 {
		return fmt.Errorf("caddy API returned error status: %s", resp.Status)
	}

	return nil
}
