package deployer

import (
	"fmt"
	"os"
	"path/filepath"

	"gorun/internal/store"
)

const defaultGoDockerfile = `# Auto-generated by Gorun PaaS
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download 2>/dev/null || true
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
`

// GenerateDockerfile checks if a Dockerfile exists in projectPath.
// If not, it generates a standard multi-stage Dockerfile for Go applications.
// Returns true if a new Dockerfile was created, false if it already existed.
func GenerateDockerfile(projectPath string) (bool, error) {
	dockerfilePath := filepath.Join(projectPath, "Dockerfile")

	if _, err := os.Stat(dockerfilePath); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("failed to check Dockerfile: %w", err)
	}

	if err := os.WriteFile(dockerfilePath, []byte(defaultGoDockerfile), 0644); err != nil {
		return false, fmt.Errorf("failed to write Dockerfile: %w", err)
	}

	return true, nil
}

// ImageName returns the standard Docker image tag for a project.
func ImageName(projectID int64) string {
	return fmt.Sprintf("gorun-img-%d", projectID)
}

// ContainerName returns the standard Docker container name for a project.
func ContainerName(projectID int64) string {
	return fmt.Sprintf("gorun-app-%d", projectID)
}

// HostPort returns the deterministic host port for a project.
func HostPort(projectID int64) int {
	return int(8000 + projectID)
}

// BuildDockerRunArgs constructs the arguments for `docker run`.
func BuildDockerRunArgs(projectID int64, envs []*store.ProjectEnv) []string {
	args := []string{
		"run",
		"-d",
		"--name", ContainerName(projectID),
		"-p", fmt.Sprintf("%d:8080", HostPort(projectID)),
	}

	for _, env := range envs {
		args = append(args, "-e", fmt.Sprintf("%s=%s", env.Key, env.Value))
	}

	args = append(args, ImageName(projectID))
	return args
}
