package deployer

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"

	"gorun/internal/store"
)

const defaultGoDockerfile = `# Auto-generated by Gorun PaaS
FROM golang:1.22-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download 2>/dev/null || true
RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/main .
EXPOSE 8080
CMD ["./main"]
`

// GenerateDockerfile checks if a Dockerfile exists in projectPath.
// If not, it generates a standard multi-stage Dockerfile for Go applications.
// Returns true if a new Dockerfile was created, false if it already existed.
func GenerateDockerfile(projectPath string) (bool, error) {
	dockerfilePath := filepath.Join(projectPath, "Dockerfile")

	if _, err := os.Stat(dockerfilePath); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("failed to check Dockerfile: %w", err)
	}

	if err := os.WriteFile(dockerfilePath, []byte(defaultGoDockerfile), 0644); err != nil {
		return false, fmt.Errorf("failed to write Dockerfile: %w", err)
	}

	return true, nil
}

// ImageName returns the standard Docker image tag for a project.
func ImageName(projectID int64) string {
	return fmt.Sprintf("gorun-img-%d", projectID)
}

// ContainerName returns the standard Docker container name for a project.
func ContainerName(projectID int64, color string) string {
	return fmt.Sprintf("gorun-app-%d-%s", projectID, color)
}

// HostPort returns the deterministic host port for a project depending on color.
func HostPort(projectID int64, color string) int {
	if color == "green" {
		return int(9000 + projectID)
	}
	return int(8000 + projectID) // blue
}

// BuildDockerRunArgs constructs the arguments for `docker run`.
func BuildDockerRunArgs(projectID int64, color string, envs []*store.ProjectEnv) []string {
	args := []string{
		"run",
		"-d",
		"--name", ContainerName(projectID, color),
		"-p", fmt.Sprintf("%d:8080", HostPort(projectID, color)),
	}

	for _, env := range envs {
		args = append(args, "-e", fmt.Sprintf("%s=%s", env.Key, env.Value))
	}

	args = append(args, ImageName(projectID))
	return args
}

// GetActiveColor checks which container (blue or green) is currently running.
func GetActiveColor(projectID int64) string {
	blueName := ContainerName(projectID, "blue")
	cmd := exec.Command("docker", "ps", "-q", "-f", fmt.Sprintf("name=%s", blueName))
	if out, _ := cmd.Output(); len(out) > 0 {
		return "blue"
	}
	greenName := ContainerName(projectID, "green")
	cmd = exec.Command("docker", "ps", "-q", "-f", fmt.Sprintf("name=%s", greenName))
	if out, _ := cmd.Output(); len(out) > 0 {
		return "green"
	}
	return ""
}

// StreamContainerLogs streams runtime logs of a project's Docker container via Server-Sent Events.
func StreamContainerLogs(ctx context.Context, projectID int64, w io.Writer, flusher http.Flusher) error {
	color := GetActiveColor(projectID)
	if color == "" {
		color = "blue" // default fallback if neither running
	}
	container := ContainerName(projectID, color)
	cmd := exec.CommandContext(ctx, "docker", "logs", "-f", "--tail", "50", container)

	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("failed to get stdout pipe: %w", err)
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("failed to get stderr pipe: %w", err)
	}

	if err := cmd.Start(); err != nil {
		return fmt.Errorf("failed to start docker logs: %w", err)
	}

	go func() {
		<-ctx.Done()
		if cmd.Process != nil {
			_ = cmd.Process.Kill()
		}
	}()

	reader := io.MultiReader(stdout, stderr)
	scanner := bufio.NewScanner(reader)

	for scanner.Scan() {
		select {
		case <-ctx.Done():
			return ctx.Err()
		default:
			line := scanner.Text()
			fmt.Fprintf(w, "data: %s\n\n", line)
			if flusher != nil {
				flusher.Flush()
			}
		}
	}

	if err := scanner.Err(); err != nil {
		return err
	}

	return cmd.Wait()
}
